services:
  - type: web
    name: phogo-ultra-bot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: "8000"
