services:
  - type: web
    name: ai-agency-mall
    env: docker
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: mall-redis-cache
          envVarKey: REDIS_URL

  - type: redis
    name: mall-redis-cache
    plan: free
    maxmemoryPolicy: allkeys-lru
